/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JOptionPane;
import Business.BookingDirectory;
import Business.Customer;
import Business.Fleet;
import Business.Booking;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author info
 */
public class AddBooking_SeatJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAccontJPanel
     */
    private BookingDirectory bookingDir;
    private Fleet fleet;
    private Customer customer;
    private Booking booking;
    private JPanel rightPanel;
    private ArrayList<String> seats = new ArrayList<String>();
    private String[] seatlocations = {"A", "B", "C", "D", "E", "F"};

    public AddBooking_SeatJPanel(JPanel rightPanel, Customer customer, Fleet fleet, BookingDirectory bookingDir) {
        initComponents();
        this.bookingDir = bookingDir;
        this.fleet = fleet;
        this.customer = customer;
        this.rightPanel = rightPanel;
        lblCustomersSelected.setText(customer.getName());
        lblFlight.setText(fleet.getAirline() + " " + fleet.getFleetId() + " " + fleet.getSource() + " --> " + fleet.getDestination());

        createseats();
        populateseats();

    }

    private BufferedImage resize(BufferedImage originalImage, int newW, int newH) {
        BufferedImage resizedImage = new BufferedImage(newW, newH, BufferedImage.TYPE_INT_ARGB);

        Graphics2D g2d = resizedImage.createGraphics();
        g2d.drawImage(originalImage, 0, 0, newW, newH, null);
        g2d.dispose();

        return resizedImage;
    }

    public void createseats() {
        for (String a : seatlocations) {
            for (int i = 1; i <= 25; i++) {
                seats.add(a + i);
            }
        }

        Iterator itr = seats.iterator();
        while (itr.hasNext()) {
            String x = (String) itr.next();
            booking = bookingDir.searchBookingbyFlightSeat(fleet.getFleetId(), x);
            if (booking != null) {
                itr.remove();
            }
        }

    }

    public void populateseats() {
        cbSeatNumber.removeAllItems();
        if ("Window".equals(cbSeatLocation.getSelectedItem().toString())) {
            for (String a : seats) {
                if (a.contains("A") || a.contains("F")) {
                    cbSeatNumber.addItem(a);
                }
            }
        } else if ("Middle".equals(cbSeatLocation.getSelectedItem().toString())) {
            for (String a : seats) {
                if (a.contains("B") || a.contains("E")) {
                    cbSeatNumber.addItem(a);
                }
            }
        } else {
            for (String a : seats) {
                if (a.contains("C") || a.contains("D")) {
                    cbSeatNumber.addItem(a);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHead = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnBookFlight = new javax.swing.JButton();
        lblCustomersSelectedTitle = new javax.swing.JLabel();
        lblCustomersSelected = new javax.swing.JLabel();
        lblFlight = new javax.swing.JLabel();
        lblFlightTitle = new javax.swing.JLabel();
        cbSeatNumber = new javax.swing.JComboBox();
        lblSeatNumber = new javax.swing.JLabel();
        lblSeatLocation = new javax.swing.JLabel();
        cbSeatLocation = new javax.swing.JComboBox();
        lblflightmap = new javax.swing.JLabel();
        btnFlightSeatMap = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setPreferredSize(new java.awt.Dimension(653, 405));

        lblHead.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHead.setText("Select Seat");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnBookFlight.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBookFlight.setText("Book Flight");
        btnBookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookFlightActionPerformed(evt);
            }
        });

        lblCustomersSelectedTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCustomersSelectedTitle.setForeground(new java.awt.Color(0, 51, 102));
        lblCustomersSelectedTitle.setText("Customer Selected:");

        lblCustomersSelected.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCustomersSelected.setForeground(new java.awt.Color(0, 0, 204));

        lblFlight.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFlight.setForeground(new java.awt.Color(0, 0, 204));

        lblFlightTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFlightTitle.setForeground(new java.awt.Color(0, 51, 102));
        lblFlightTitle.setText("Flight Selected:");

        lblSeatNumber.setText("Seat Number*");

        lblSeatLocation.setText("Seat Location*");

        cbSeatLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Window", "Middle", "Aisle" }));
        cbSeatLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSeatLocationActionPerformed(evt);
            }
        });

        btnFlightSeatMap.setText("Flight Seat Map");
        btnFlightSeatMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightSeatMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCustomersSelectedTitle)
                        .addGap(18, 18, 18)
                        .addComponent(lblCustomersSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFlightSeatMap)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFlightTitle)
                                .addGap(18, 18, 18)
                                .addComponent(lblFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHead)
                                        .addGap(114, 114, 114))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSeatLocation)
                                            .addComponent(lblSeatNumber))
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbSeatNumber, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbSeatLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(lblflightmap)))
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBookFlight)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCustomersSelectedTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCustomersSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFlightTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnFlightSeatMap)
                                .addGap(35, 35, 35)
                                .addComponent(lblflightmap))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(lblHead)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSeatLocation)
                                    .addComponent(cbSeatLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(176, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBookFlight)
                            .addComponent(btnBack))
                        .addGap(111, 111, 111))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        cardLayout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookFlightActionPerformed
        // TODO add your handling code here:
        if ("".equals(cbSeatNumber.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Please fill all the required fields.");
            return;
        }
        Booking booking = bookingDir.addBooking();
        booking.setCustomerEmail(customer.getEmail());
        booking.setAirlineName(fleet.getAirline());
        booking.setAircraftName(fleet.getFleetId());
        booking.setSeat(cbSeatNumber.getSelectedItem().toString());
        fleet.setSeatLeft(fleet.getSeatLeft() - 1);
        JOptionPane.showMessageDialog(null, "Flight Added Successfully");
        rightPanel.removeAll();
    }//GEN-LAST:event_btnBookFlightActionPerformed

    private void cbSeatLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSeatLocationActionPerformed
        // TODO add your handling code here:
        populateseats();
    }//GEN-LAST:event_cbSeatLocationActionPerformed

    private void btnFlightSeatMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightSeatMapActionPerformed
        // TODO add your handling code here:
        try {
            JFrame frame = new JFrame();
            File sourceimage = new File("c:\\FlightSeatMap.png");
            BufferedImage image = ImageIO.read(sourceimage);
            JLabel lbl = new JLabel(new ImageIcon(image));
            frame.getContentPane().add(new JScrollPane(lbl));
            frame.setSize(400, 600);
            frame.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AddBooking_SeatJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFlightSeatMapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookFlight;
    private javax.swing.JButton btnFlightSeatMap;
    private javax.swing.JComboBox cbSeatLocation;
    private javax.swing.JComboBox cbSeatNumber;
    private javax.swing.JLabel lblCustomersSelected;
    private javax.swing.JLabel lblCustomersSelectedTitle;
    private javax.swing.JLabel lblFlight;
    private javax.swing.JLabel lblFlightTitle;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblSeatLocation;
    private javax.swing.JLabel lblSeatNumber;
    private javax.swing.JLabel lblflightmap;
    // End of variables declaration//GEN-END:variables
}
