/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JOptionPane;
import Business.Fleet;
import Business.Airline;
import Business.FleetDirectory;
import Business.AirlineDirectory;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author info
 */
public class AddFleetJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAccontJPanel
     */
    private AirlineDirectory airlineDir;
    private FleetDirectory fleetDir;
    private JPanel rightPanel;

    public AddFleetJPanel(JPanel rightPanel, AirlineDirectory airlineDir, FleetDirectory fleetDir) {
        initComponents();
        this.airlineDir = airlineDir;
        this.fleetDir = fleetDir;
        this.rightPanel = rightPanel;

        for (Airline a : airlineDir.getAirlineDirectory()) {
            cbAirline.addItem(a.getName());
            cbAirline.setSelectedIndex(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHead = new javax.swing.JLabel();
        lblAirline = new javax.swing.JLabel();
        lblDepTime = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        lblDest = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cbAirline = new javax.swing.JComboBox();
        cbDepTime = new javax.swing.JComboBox();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));

        lblHead.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHead.setText("Add Flight");

        lblAirline.setText("Airline*");

        lblDepTime.setText("Departure Time*");

        lblSource.setText("Source*");

        lblDest.setText("Destination*");

        btnCreate.setText(" Add Flight");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cbDepTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Morning", "Evening", "Night" }));

        lblDate.setText("Date*");

        jLabel1.setText("(MM/DD/YYYY format)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lblHead))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(btnCreate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAirline)
                                .addComponent(lblDepTime)
                                .addComponent(lblSource)
                                .addComponent(lblDest)
                                .addComponent(lblDate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(20, 20, 20)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDate)
                            .addComponent(txtSource, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(txtDestination)
                            .addComponent(cbAirline, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbDepTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblHead)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirline)
                    .addComponent(cbAirline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepTime, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDepTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSource)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDest)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addGap(22, 22, 22)
                .addComponent(btnBack)
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        Date date;
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        if (txtDestination.getText().isEmpty() || txtSource.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all the required fields.");
            return;
        }

        if (txtSource.getText().trim().toLowerCase().equals(txtDestination.getText().trim().toLowerCase())) {
            JOptionPane.showMessageDialog(null, "Source and Destination cannot be same");
            return;
        }

        try {
            sdf.setLenient(false);
            date = sdf.parse(txtDate.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter date in MM/dd/yyyy");
            return;
        }

        if (date.before(new Date())) {
            JOptionPane.showMessageDialog(null, "Date of the flight cannot be in the past");
            return;
        }

        Fleet fleet = fleetDir.addFleet();
        fleet.setAirline(cbAirline.getSelectedItem().toString());
        fleet.setDepartureTime(cbDepTime.getSelectedItem().toString());
        fleet.setSource(txtSource.getText());
        fleet.setDestination(txtDestination.getText());
        fleet.setFlightDate(date);
        fleet.setSeatLeft(150);
        for (Airline a : airlineDir.getAirlineDirectory()) {
            if (a.getName() == cbAirline.getSelectedItem().toString()) {
                int fleetCount = a.getFleetCount();
                fleetCount = fleetCount + 1;
                a.setFleetCount(fleetCount);
                fleet.setFleetId(a.getAirlinePrefix() + " " + Integer.toString(fleetCount));
            }
        }
        JOptionPane.showMessageDialog(null, "Flight Added Successfully");

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        cardLayout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox cbAirline;
    private javax.swing.JComboBox cbDepTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAirline;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDepTime;
    private javax.swing.JLabel lblDest;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblSource;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
