/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.TravelAgencyMain;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author info
 */
public class AirlineManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountManagementPanel
     */
    private TravelAgencyMain travelAgency;
    private JPanel rightPanel;

    public AirlineManagementPanel(JPanel rightPanel, TravelAgencyMain travelAgency) {
        initComponents();
        this.travelAgency = travelAgency;
        this.rightPanel = rightPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateAirline = new javax.swing.JButton();
        btnManageAirline = new javax.swing.JButton();
        btnAddAircraft = new javax.swing.JButton();
        btnManageAircraft = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));

        btnCreateAirline.setText("Add Airline");
        btnCreateAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirlineActionPerformed(evt);
            }
        });

        btnManageAirline.setText("Manage Airline");
        btnManageAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAirlineActionPerformed(evt);
            }
        });

        btnAddAircraft.setText("Add Aircraft");
        btnAddAircraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAircraftActionPerformed(evt);
            }
        });

        btnManageAircraft.setText("Manage Aircraft");
        btnManageAircraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAircraftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddAircraft, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnManageAircraft, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnManageAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAirline)
                    .addComponent(btnManageAirline))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAircraft)
                    .addComponent(btnManageAircraft))
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirlineActionPerformed
        // TODO add your handling code here:
        AddAirlineJPanel createPanel = new AddAirlineJPanel(rightPanel, travelAgency.getAirlineDir());
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        rightPanel.add(createPanel);
        cardLayout.next(rightPanel);
    }//GEN-LAST:event_btnCreateAirlineActionPerformed

    private void btnManageAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAirlineActionPerformed
        // TODO add your handling code here:
        ManageAirlinePanel manageAirlinePanel = new ManageAirlinePanel(rightPanel, travelAgency.getAirlineDir(), travelAgency.getFleetDir());
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        rightPanel.add(manageAirlinePanel);
        cardLayout.next(rightPanel);
    }//GEN-LAST:event_btnManageAirlineActionPerformed

    private void btnAddAircraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAircraftActionPerformed
        // TODO add your handling code here:
        AddFleetJPanel createPanel = new AddFleetJPanel(rightPanel, travelAgency.getAirlineDir(), travelAgency.getFleetDir());
        //rightSplitPane.setRightComponent(amPanel);
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        rightPanel.add(createPanel);
        cardLayout.next(rightPanel);
    }//GEN-LAST:event_btnAddAircraftActionPerformed

    private void btnManageAircraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAircraftActionPerformed
        // TODO add your handling code here:
        ManageFleetPanel manageFleetPanel = new ManageFleetPanel(rightPanel, travelAgency.getAirlineDir(), travelAgency.getFleetDir(), travelAgency.getBookingDir());
        //rightSplitPane.setRightComponent(amPanel);
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        rightPanel.add(manageFleetPanel);
        cardLayout.next(rightPanel);
    }//GEN-LAST:event_btnManageAircraftActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAircraft;
    private javax.swing.JButton btnCreateAirline;
    private javax.swing.JButton btnManageAircraft;
    private javax.swing.JButton btnManageAirline;
    // End of variables declaration//GEN-END:variables
}
