/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.TravelAgencyMain;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author info
 */
public class BookingManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountManagementPanel
     */
    private TravelAgencyMain travelAgency;
    private JPanel rightPanel;

    public BookingManagementPanel(JPanel rightPanel, TravelAgencyMain travelAgency) {
        initComponents();
        this.travelAgency = travelAgency;
        this.rightPanel = rightPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBookFlight = new javax.swing.JButton();
        btnManageFlight = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));

        btnBookFlight.setText("Book Flight");
        btnBookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookFlightActionPerformed(evt);
            }
        });

        btnManageFlight.setText("Manage Flights");
        btnManageFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnBookFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookFlight)
                    .addComponent(btnManageFlight))
                .addContainerGap(321, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookFlightActionPerformed
        // TODO add your handling code here:
        AddBooking_CustomerJPanel createPanel = new AddBooking_CustomerJPanel(rightPanel, travelAgency);
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        rightPanel.add(createPanel);
        cardLayout.next(rightPanel);
    }//GEN-LAST:event_btnBookFlightActionPerformed

    private void btnManageFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFlightActionPerformed
        // TODO add your handling code here:
        ManageBookingPanel manageBookingPanel = new ManageBookingPanel(rightPanel, travelAgency);
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        rightPanel.add(manageBookingPanel);
        cardLayout.next(rightPanel);
    }//GEN-LAST:event_btnManageFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookFlight;
    private javax.swing.JButton btnManageFlight;
    // End of variables declaration//GEN-END:variables
}
