/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.TravelAgencyMain;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author info
 */
public class CustomerManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountManagementPanel
     */
    private TravelAgencyMain travelAgency;
    private JPanel rightPanel;

    public CustomerManagementPanel(JPanel rightPanel, TravelAgencyMain travelAgency) {
        initComponents();
        this.travelAgency = travelAgency;
        this.rightPanel = rightPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddCustomer = new javax.swing.JButton();
        btnManageCustomer = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));

        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnManageCustomer.setText("Manage Customers");
        btnManageCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageCustomer)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCustomer)
                    .addComponent(btnManageCustomer))
                .addContainerGap(321, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
        AddCustomerJPanel createPanel = new AddCustomerJPanel(rightPanel, travelAgency.getCustomerDir());
        //rightSplitPane.setRightComponent(amPanel);
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        rightPanel.add(createPanel);
        cardLayout.next(rightPanel);
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnManageCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomerActionPerformed
        // TODO add your handling code here:
        ManageCustomerPanel manageProdPanel = new ManageCustomerPanel(rightPanel, travelAgency.getCustomerDir(), travelAgency.getBookingDir());
        //rightSplitPane.setRightComponent(amPanel);
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        rightPanel.add(manageProdPanel);
        cardLayout.next(rightPanel);
    }//GEN-LAST:event_btnManageCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnManageCustomer;
    // End of variables declaration//GEN-END:variables
}
