/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.TravelAgencyMain;
import java.awt.CardLayout;

/**
 *
 * @author info
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private TravelAgencyMain travelAgency;

    public MainJFrame() {
        initComponents();
        travelAgency = new TravelAgencyMain();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightSplitPane = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        btnCustomerManager = new javax.swing.JButton();
        btnAirlineManager = new javax.swing.JButton();
        btnBookingManager = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPanel.setBackground(new java.awt.Color(255, 204, 204));

        btnCustomerManager.setText("Customer Manager");
        btnCustomerManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerManagerActionPerformed(evt);
            }
        });

        btnAirlineManager.setText("Airline Manager");
        btnAirlineManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlineManagerActionPerformed(evt);
            }
        });

        btnBookingManager.setText("Booking Manager");
        btnBookingManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(btnCustomerManager)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnBookingManager, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(leftPanelLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(btnAirlineManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnCustomerManager)
                .addGap(125, 125, 125)
                .addComponent(btnBookingManager)
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(leftPanelLayout.createSequentialGroup()
                    .addGap(144, 144, 144)
                    .addComponent(btnAirlineManager)
                    .addContainerGap(225, Short.MAX_VALUE)))
        );

        rightSplitPane.setLeftComponent(leftPanel);

        rightPanel.setLayout(new java.awt.CardLayout());
        rightSplitPane.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerManagerActionPerformed
        // TODO add your handling code here:
        CustomerManagementPanel cmPanel = new CustomerManagementPanel(rightPanel, travelAgency);
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        rightPanel.add(cmPanel);
        cardLayout.next(rightPanel);
    }//GEN-LAST:event_btnCustomerManagerActionPerformed

    private void btnAirlineManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlineManagerActionPerformed
        // TODO add your handling code here:
        AirlineManagementPanel amPanel = new AirlineManagementPanel(rightPanel, travelAgency);
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        rightPanel.add(amPanel);
        cardLayout.next(rightPanel);
    }//GEN-LAST:event_btnAirlineManagerActionPerformed

    private void btnBookingManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingManagerActionPerformed
        // TODO add your handling code here:
        BookingManagementPanel bmPanel = new BookingManagementPanel(rightPanel, travelAgency);
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        rightPanel.add(bmPanel);
        cardLayout.next(rightPanel);
    }//GEN-LAST:event_btnBookingManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAirlineManager;
    private javax.swing.JButton btnBookingManager;
    private javax.swing.JButton btnCustomerManager;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JSplitPane rightSplitPane;
    // End of variables declaration//GEN-END:variables
}
